{% set name = "memory_graph" %}
{% set version = "0.3.46" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9715b1afc19d87d3025db5c10ddb96150b291d7545c3c4ce8c88fad492d8732f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - python-graphviz

test:
  imports:
    - memory_graph
    - graphviz
  commands:
    - dot -V
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    - graphviz
    - python-graphviz

about:
  home: https://pypi.org/project/memory_graph/
  summary: "Visualize Python data using Graphviz."
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    Teaching tool and debugging aid in context of references, mutable data types, and shallow and deep copy.
  dev_url: https://github.com/bterwijn/memory_graph
  doc_url: https://github.com/bterwijn/memory_graph#readme

extra:
  recipe-maintainers:
    - bterwijn
